export const Users = [
    {
        "id": 1,
        "first_name": "One",
        "last_name": "A",
        "email": "one@gmail.com",
        "gender": "female",
    },
    {
        "id": 2,
        "first_name": "Two",
        "last_name": "B",
        "email": "two@gmail.com",
        "gender": "male",
    },
    {
        "id": 3,
        "first_name": "Three",
        "last_name": "C",
        "email": "three@gmail.com",
        "gender": "female",
    },
    {
        "id": 4,
        "first_name": "Four",
        "last_name": "D",
        "email": "four@gmail.com",
        "gender": "male",
    },
    {
        "id": 5,
        "first_name": "Five",
        "last_name": "E",
        "email": "five@gmail.com",
        "gender": "female",
    },
    {
        "id": 6,
        "first_name": "Six",
        "last_name": "F",
        "email": "six@gmail.com",
        "gender": "male",
    },
    {
        "id": 7,
        "first_name": "Seven",
        "last_name": "G",
        "email": "seven@gmail.com",
        "gender": "female",
    },
    {
        "id": 8,
        "first_name": "Eight",
        "last_name": "H",
        "email": "eight@gmail.com",
        "gender": "male",
    },
    {
        "id": 9,
        "first_name": "Nine",
        "last_name": "I",
        "email": "nine@gmail.com",
        "gender": "female",
    },
    {
        "id": 10,
        "first_name": "Ten",
        "last_name": "K",
        "email": "ten@gmail.com",
        "gender": "male",
    },
]